version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./todo-backend
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/todo_app
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
